name: Tauri Android Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "App Version 0.0"
        required: true
      release_notes:
        description: "Release Notes"
        required: false

env:
  VERSION: ${{ github.event.inputs.version }}
  RELEASE_NOTES: ${{ github.event.inputs.release_notes }}

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build and Deploy to Google Play

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Prepare Android keystore
        run: |
          mkdir -p src-tauri/gen
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > src-tauri/gen/upload-keystore.jks

      - name: Write keystore.properties
        run: |
          cat <<EOF > src-tauri/gen/keystore.properties
          password=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=src-tauri/gen/upload-keystore.jks
          EOF

      - name: Build Tauri Android APK
        run: pnpm tauri android build --target aarch64-linux-android

      - name: Decode Google Play service account
        run: echo "${{ secrets.GOOGLE_PLAY_KEY }}" | base64 -d > /tmp/play-account.json

      - name: Upload to Google Play Internal Track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: /tmp/play-account.json
          packageName: com.yourcompany.yourapp
          releaseFiles: ./src-tauri/gen/android/app/build/outputs/apk/release/app-release.apk
          track: internal
          status: completed
        env:
          RELEASE_NAME: v${{ github.event.inputs.version }}
